// <auto-generated />
using System;
using MatchDataManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchDataManager.Api.Database
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20221128203829_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CityOfPublish")
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearOFPublish")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BookTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d2b0228-4d0d-4c23-8b49-01a698857799"),
                            Author = "Alan Walk",
                            BookName = "New Story Book",
                            CityOfPublish = "Gliwice",
                            IdKey = 1,
                            YearOFPublish = "2022"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
