// <auto-generated />
using System;
using MatchDataManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchDataManager.Api.Database
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("MatchDataManager.Api.Models.Location", b =>
                {
                    b.Property<int>("IdKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("IdKey");

                    b.ToTable("LocationTable");

                    b.HasData(
                        new
                        {
                            IdKey = 1,
                            City = "poznan",
                            Id = new Guid("9d2b0228-4d0d-4c23-8b49-01a698857799"),
                            Name = "emi"
                        });
                });

            modelBuilder.Entity("MatchDataManager.Api.Models.Team", b =>
                {
                    b.Property<int>("IdKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachName")
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("IdKey");

                    b.ToTable("TeamTable");

                    b.HasData(
                        new
                        {
                            IdKey = 1,
                            CoachName = "elon",
                            Id = new Guid("9d2b0228-4d0d-4c23-8b49-01a698857709"),
                            Name = "domi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
